name: jimtl_codegen
description: Intl utility to generate ARB files from Dart intl class
version: 0.0.4
homepage: https://github.com/jaumard/jimtl
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  analyzer: ">=2.1.0 <8.0.0"
  build: ">=2.0.1 <3.0.0"
  path: ">=1.8.0 <2.0.0"
  source_gen: ">=1.0.0 <2.0.0"
  # intl: ">=0.17.0 <1.0.0"
  intl: ^0.20.2
  intl_generator:
    git:
      url: https://github.com/Elr03/intl_generator.git
  #path: ../../../../StudioProjects/intl_translation
  jimtl:
    git:
      url: https://github.com/Elr03/jimtl.git
      path: packages/jimtl

dev_dependencies:
  build_runner: ^2.3.3
  test: ^1.16.8
